Декоративные элементы главной страницы
htmlacademy-htmlcss/1566267-technomart-29 pull request #10
Opened 2020-10-05 11:28 UTC by stLucky

2020-10-06 19:12 UTC, mikhin commented
https://github.com/htmlacademy-htmlcss/1566267-technomart-29/pull/10/files#diff-6a6a912d0c7b55b537768da778032849R1461

color: var(--basic-black-opacity-03);

Такой переменной нет)

2020-10-06 19:18 UTC, mikhin commented
<img width="147" alt="Снимок экрана 2020-10-06 в 22 18 06" src="https://user-images.githubusercontent.com/38258318/95249768-d971f800-0821-11eb-9656-f8bd384b4ac9.png">

Наверняка тут не будет вплотную инпут прилегать — давай сразу бахнем марджины с обеих сторон?)

2020-10-06 19:22 UTC, mikhin commented
Необязательно, но просто для раздумия, вдруг будет хорошая мысль — вынести дублирование кода в какие-либо общие классы:

<img width="872" alt="Снимок экрана 2020-10-06 в 22 20 51" src="https://user-images.githubusercontent.com/38258318/95250171-62892f00-0822-11eb-95e3-e8917afcdf2e.png">
<img width="877" alt="Снимок экрана 2020-10-06 в 22 20 45" src="https://user-images.githubusercontent.com/38258318/95250054-42597000-0822-11eb-8d5f-349d836351a0.png">
<img width="887" alt="Снимок экрана 2020-10-06 в 22 20 39" src="https://user-images.githubusercontent.com/38258318/95250050-41c0d980-0822-11eb-9931-f61e90771c0c.png">
<img width="869" alt="Снимок экрана 2020-10-06 в 22 20 28" src="https://user-images.githubusercontent.com/38258318/95250041-3f5e7f80-0822-11eb-9817-0cc3dfbc3248.png">

2020-10-07 07:59 UTC, mikhin requested changes

2020-10-08 07:48 UTC, mikhin commented
<img width="484" alt="Снимок экрана 2020-10-08 в 10 45 18" src="https://user-images.githubusercontent.com/38258318/95429686-67013500-0953-11eb-8a3c-52dd51207db3.png">

Моя IDE подсказывает что эти селекторы не используются, просто для заметки)

2020-10-08 07:56 UTC, mikhin approved these changes

2020-10-08 07:56 UTC, mikhin commented on css/style.css
> +.authorized-user-menu__link
Вот тут опечатка)

2020-10-08 07:56 UTC, mikhin commented on index.html
> +                <li><button class="useraction-menu__button useraction-menu__button_type_cart" type="button">Купить</a>
Ошибка закрытия тега

2020-10-08 07:56 UTC, mikhin commented on index.html
> +                <li><button class="useraction-menu__button useraction-menu__button_type_cart" type="button">Купить</a>
Для всех подобных элементов)

2020-10-08 07:56 UTC, mikhin commented on css/style.css
> +.shop-menu__item_mark_new::before {
Это полностью дублирует вот это `.catalogues-content__item_mark_new::before`. Давай сделаем это отдельным БЭМ-блоком? А позиционирование оставим на элементе)

2020-10-08 07:56 UTC, mikhin commented on index.html
>              <input class="search-form__input" type="search" placeholder="Поиск">
Я думаю время пришло) Давай добавим label?)

2020-10-08 07:57 UTC, merged

2020-10-08 09:31 UTC, stLucky commented
> <img alt="Снимок экрана 2020-10-08 в 10 45 18" width="484" src="https://user-images.githubusercontent.com/38258318/95429686-67013500-0953-11eb-8a3c-52dd51207db3.png">
> 
> Моя IDE подсказывает что эти селекторы не используются, просто для заметки)

это относится к странице каталога)